return {
  -- stylua: ignore
  kind = {
    Text          = "",
    Method        = "",
    Function      = "",
    Constructor   = "",
    Field         = "",
    Variable      = "",
    Class         = "",
    Interface     = "",
    Module        = "",
    Property      = "ﰠ",
    Unit          = "塞",
    Value         = "",
    Enum          = "",
    Keyword       = "",
    Snippet       = "",
    Color         = "",
    File          = "",
    Reference     = "",
    Folder        = "",
    EnumMember    = "",
    Constant      = "",
    Struct        = "פּ",
    Event         = "",
    Operator      = "",
    TypeParameter = "",
  },
  -- stylua: ignore
  type = {
    Boolean = "﨡",
    Number  = "",
    String  = "𝓐",
    Array   = "",
    Object  = "⦿",
  },
  -- stylua: ignore
  documents = {
    File            = "",
    Files           = "",
    Symlink         = "",
    Folder          = "",
    FolderOpen      = "",
    EmptyFolder     = "",
    EmptyFolderOpen = "",
    SymlinkFolder   = "",
  },
  -- stylua: ignore
  other_symbols = {
    Namespace = "",
    Package   = "",
    Key       = "🔐",
    Null      = "NULL",
  },
  -- stylua: ignore
  git = {
    Add       = "",
    Staged    = "",
    Mod       = "",
    Remove    = "",
    Unmerged  = "",
    Untracked = "U",
    Ignore    = "",
    Rename    = "",
    Diff      = "",
    Repo      = "",
    Octoface  = "",
  },
  -- stylua: ignore
  ui = {
    Letter            = "",
    ArrowClosed       = "",
    ArrowOpen         = "",
    Lock              = "",
    Circle            = "●",
    BigCircle         = "",
    BigUnfilledCircle = "",
    Close             = "",
    NewFile           = "",
    FindFile          = "",
    Search            = "",
    Lightbulb         = "",
    Project           = "",
    Dashboard         = "",
    Clock1            = "",
    Clock2            = "",
    Clock3            = "",
    Comment           = "",
    Bug               = "",
    Code              = "",
    Enter             = "﬌",
    GoTo              = "",
    Telescope         = "",
    Gear              = "",
    Refresh           = "",
    Socket            = "",
    Package           = "",
    List              = "",
    SignIn            = "",
    SignOut           = "",
    Check             = "",
    Fire              = "",
    Note              = "",
    BookMark          = "",
    Pencil1           = "",
    Pencil2           = "✎",
    ChevronRight      = "",
    Table             = "",
    Calendar          = "",
    CloudDownload     = "",
  },
  -- stylua: ignore
  diagnostics = {
    Error       = "",
    Warning     = "",
    Information = "",
    Question    = "",
    Hint        = "",
  },
  -- stylua: ignore
  misc = {
    Robot    = "ﮧ",
    Squirrel = "",
    Tag      = "",
    Watch    = "",
    Smiley   = "ﲃ",
  },
}
