return {
  -- stylua: ignore
  kind = {
    Text          = "",
    Method        = "",
    Function      = "",
    Constructor   = "",
    Field         = "",
    Variable      = "",
    Class         = "",
    Interface     = "",
    Module        = "",
    Property      = "ﰠ",
    Unit          = "塞",
    Value         = "",
    Enum          = "",
    Keyword       = "",
    Snippet       = "",
    Color         = "",
    File          = "",
    Reference     = "",
    Folder        = "",
    EnumMember    = "",
    Constant      = "",
    Struct        = "פּ",
    Event         = "",
    Operator      = "",
    TypeParameter = "",
  },
  -- stylua: ignore
  type = {
    Array   = "",
    Number  = "",
    String  = "𝓐",
    Boolean = "﨡",
    Object  = "⦿",
  },
  -- stylua: ignore
  documents = {
    File       = "",
    Files      = "",
    Folder     = "",
    OpenFolder = "",
  },
  -- stylua: ignore
  git = {
    Add      = "",
    Mod      = "",
    Remove   = "",
    Ignore   = "",
    Rename   = "",
    Diff     = "",
    Repo     = "",
    Octoface = "",
  },
  -- stylua: ignore
  ui = {
    ArrowClosed       = "",
    ArrowOpen         = "",
    Lock              = "",
    Circle            = "●",
    BigCircle         = "",
    BigUnfilledCircle = "",
    Close             = "",
    NewFile           = "",
    Search            = "",
    Lightbulb         = "",
    Project           = "",
    Dashboard         = "",
    History           = "",
    Comment           = "",
    Bug               = "",
    Code              = "",
    Telescope         = "",
    Gear              = "",
    Package           = "",
    List              = "",
    SignIn            = "",
    SignOut           = "",
    Check             = "",
    Fire              = "",
    Note              = "",
    BookMark          = "",
    Pencil            = "",
    ChevronRight      = "",
    Table             = "",
    Calendar          = "",
    CloudDownload     = "",
  },
  -- stylua: ignore
  diagnostics = {
    Error       = "",
    Warning     = "",
    Information = "",
    Question    = "",
    Hint        = "",
  },
  -- stylua: ignore
  misc = {
    Robot    = "ﮧ",
    Squirrel = "",
    Tag      = "",
    Watch    = "",
    Smiley   = "ﲃ",
  },
}
