vim.g.symbols_outline = {
  width = 35,
  --stylua: ignore
  symbols = {
    File          = { icon = "", hl = "TSURI" },
    Module        = { icon = "", hl = "TSNamespace" },
    Namespace     = { icon = "", hl = "TSNamespace" },
    Package       = { icon = "", hl = "TSNamespace" },
    Class         = { icon = "", hl = "TSType" },
    Method        = { icon = "", hl = "TSMethod" },
    Property      = { icon = "ﰠ", hl = "TSMethod" },
    Field         = { icon = "", hl = "TSField" },
    Constructor   = { icon = "", hl = "TSConstructor" },
    Enum          = { icon = "", hl = "TSType" },
    Interface     = { icon = "", hl = "TSType" },
    Function      = { icon = "", hl = "TSFunction" },
    Variable      = { icon = "", hl = "TSConstant" },
    Constant      = { icon = "", hl = "TSConstant" },
    String        = { icon = "𝓐", hl = "TSString" },
    Number        = { icon = "", hl = "TSNumber" },
    Boolean       = { icon = "﨡", hl = "TSBoolean" },
    Array         = { icon = "", hl = "TSConstant" },
    Object        = { icon = "⦿", hl = "TSType" },
    Key           = { icon = "🔐", hl = "TSType" },
    Null          = { icon = "NULL", hl = "TSType" },
    EnumMember    = { icon = "", hl = "TSField" },
    Struct        = { icon = "𝓢", hl = "TSType" },
    Event         = { icon = "", hl = "TSType" },
    Operator      = { icon = "", hl = "TSOperator" },
    TypeParameter = { icon = "", hl = "TSParameter" },
  },
}
